name: Build and deploy Angular app to Azure Web App - product-catalog-frontend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app
        run: npm run build --if-present

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/product-catalog-frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: ./dist

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'product-catalog-frontend'
          slot-name: 'Production'
          package: ./dist
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_0952D44B1C4249E1B03DE2A41A06EFF0 }}
