name: Angular CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Angular app (production)
      run: npm run build -- --configuration=production

    - name: Run tests
      run: npm test --if-present

    - name: Cache Angular build output
      uses: actions/cache@v3
      with:
        path: .angular/cache
        key: angular-cache-${{ hashFiles('**/package-lock.json') }}

    - name: Upload production-ready build
      uses: actions/upload-artifact@v4
      with:
        name: dist-folder
        path: dist/
