name: Angular 20 Frontend CI

on:
  push:
    branches: [ "main" ]        # ✅ Trigger workflow on push to main
  pull_request:
    branches: [ "main" ]        # ✅ Trigger workflow on PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0   # ✅ Angular 20 requires >= 20.19

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build --if-present

      - name: Run Tests
        run: npm test --if-present
